spring:
  data:
    redis:
      host: redis
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

product-service:
  url: http://product-service:8082

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
