spring:
  datasource:
    url: jdbc:postgresql://postgres-payment:5432/payment_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

iyzico:
  api-key: sandbox-jAF6LOHzIW6NPbTBbE0Sh1VZB9DBXGFE
  secret-key: sandbox-35wJhCRyZv9g7VARW33CQywejndEaviE
  base-url: https://sandbox-api.iyzipay.com
  callback-url: http://localhost:8085/api/payments/iyzico-callback
  frontend-result-url: http://localhost:5173/payment/result