server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/payment_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

iyzico:
  api-key: ${IYZICO_API_KEY:sandbox-api-key}
  secret-key: ${IYZICO_SECRET_KEY:sandbox-secret-key}
  base-url: ${IYZICO_BASE_URL:https://sandbox-api.iyzipay.com}